spring:
  application:
    name: gateway

zuul:
  ignored-services: '*'
  routes:
    firstservice:
      path: /firstservice/**
    secondservice:
      path: /secondservice/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}