spring:
  application:
    name: gateway

zuul:
  ignored-services: '*'
  routes:
    greeting:
      path: /**
      url: http://localhost:8081

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}